### PR TITLE
added trie and API repos as submodules

### PR DESCRIPTION
**Pull request by jeffreymzhou**
This will allow us to connect to the redis server and begin running our interactive and batch modes with the redid-server functionality that the redis and API teams have provided.

### CODE REVIEW

**Comment by SethDeVries** [comment]
Our fake CI shouldn't be failing for anything, really--what made it fail here?

**Comment by jeffreymzhou** [comment]
Hi Seth,

No idea, as I did not touch any of the main source code or tests.

- Jeffrey

**Comment by SethDeVries** [comment]
I think there's a CI file in one of the submodules which isn't passing? Doesn't look like it's ours that's failing. We don't want that to affect our CI builds, so could you chat w/ the API team about that?

**Comment by jeffreymzhou** [comment]
Yeah, I'll chat with them to make sure everything's good.

**Pull request closed without merging**
