### PR TITLE
changed ./minishell to ./autocomplete where the shell runs autocomplete command on startup

### PR DESCRIPTION
**Pull request by dayaffe**
see #34

### CODE REVIEW

**Comment by dayaffe** [comment]
got catch! let me fix right now

**Comment by dayaffe** [comment]
oh wait you're incorrect. make clean does not remove it because make fclean does!

**Comment by SethDeVries** [comment]
is there a reason those are separate?

**Comment by dayaffe** [comment]
I'm not sure, that is how the shell library came

**Comment by SethDeVries** [comment]
Fair enough, we can leave that to its own issue then

**Pull request merged**
